BaSP-TG-6: Create the POST and DELETE Employee with controllers and validations
BaSP-m2022/franco-trackgenix-server pull request #17
Opened 2022-05-17 11:07 UTC by AlejoGF

2022-05-17 13:08 UTC, franco-marini commented on src/validations/employees.js
> +      .pattern(/^(?=.*[a-z])(?=.*\d)/)
Revisa la regex que utilizaste ya que no esta funcionando correctmante

<img width="735" alt="Screen Shot 2022-05-17 at 10 01 06" src="https://user-images.githubusercontent.com/49521882/168816770-6cd9626d-9fbb-46cc-bc21-b669c51e2244.png">

2022-05-17 13:17 UTC, franco-marini requested changes
Te falta subir el archivo de postman

2022-05-17 13:17 UTC, franco-marini commented on src/validations/employees.js
> +  return next();
Los `return` no son necesario para estos casos

2022-05-17 17:09 UTC, franco-marini commented on src/validations/employees.js
> +      .pattern(/^(?=.*[a-z])(?=.*\d)/)
Claro, pero fijate que utilizando el regex que tenes no me marca ninguna de las lineas como correcta. 

Este es un caso que es match
<img width="727" alt="Screen Shot 2022-05-17 at 14 08 09" src="https://user-images.githubusercontent.com/49521882/168871138-42e41d3c-728d-421f-a629-5eaba59537fe.png">

2022-05-17 20:21 UTC, AlejoGF commented on src/validations/employees.js
> +  return next();
@franco-marini cuando le saco el return me tira un error a la hora de querer hacer una request y esta me sale fallida

![image](https://user-images.githubusercontent.com/96153090/168903127-fe81ced4-a9d6-4a19-b2b6-087a54b17c87.png)

2022-05-17 20:21 UTC, AlejoGF commented on src/validations/employees.js
> +  return next();
![image](https://user-images.githubusercontent.com/96153090/168903183-a51253e2-d01f-4fee-ade4-c906a9de5bec.png)

2022-05-18 14:30 UTC, franco-marini approved these changes
@AlejoGF Actualiza tu rama con la rama de master

2022-05-19 14:44 UTC, merged