BaSP-TG: SuperAdmin Backend
BaSP-m2022/franco-trackgenix-server pull request #2
Opened 2022-05-09 17:43 UTC by LucianoAlarcon

2022-05-09 19:06 UTC, franco-marini requested changes
Buen laburo Lucho, te faltan algunas cositas a revisar

2022-05-09 23:30 UTC, LucianoAlarcon commented
Ahi realice las correciones

2022-05-10 16:30 UTC, franco-marini approved these changes
🚀

2022-05-10 16:38 UTC, franco-marini requested changes
Podes revisar este caso: `localhost:3000/super-admins/?firstName=alyda&lastName=audsley`

Ya que al estar con una letra en mayuscula no devuelve nada. Revisa si utilizando el metodo `.toLowerCase()` o `.toUpperCase()` en los filtros para comparar los valores

2022-05-10 21:12 UTC, LucianoAlarcon commented
Correcciones hechas, ahi en el caso que me mandaste ya filtra correctamente y de las otras maneras siguiendo el nombre tambien. El unico caso que no filtra es si no seguis el orden de los parametros.
ej: localhost:3000/super-admins/?firstName=alyda&email=example@email.com

2022-05-10 22:53 UTC, franco-marini approved these changes

2022-05-10 22:53 UTC, merged