BaSP-TG: Create, update and filter of timesheets
BaSP-m2022/franco-trackgenix-server pull request #3
Opened 2022-05-09 21:08 UTC by Juanoauil

2022-05-09 22:35 UTC, franco-marini requested changes

2022-05-09 22:35 UTC, franco-marini commented on package.json
> +}
El archivo `package.json` no deberia recibir ningun tipo de cambio, en esta instancia

2022-05-09 22:35 UTC, franco-marini commented on src/resources/time-sheets.js
> +/* eslint-disable max-len */
Esta linea no se debe utilizar ya que no permite el uso de la regla de `max-len` en este archivo. Lo que podes hacer es correr en una terminal `npm run lint:fix` para poder arreglar todos estos errores que exceden el largo del formato. O bien podes hacer uso de lo que te mostre el viernes pasado, es decir, hacer un `enter` entre `filter((` y `(`

2022-05-09 22:35 UTC, franco-marini commented on src/resources/time-sheets.js
> +});
Debe haber 2 gets, uno con `/:id` y el otro que sea con `query params` como lo vimos hoy en la pre entrega. El cual es un unico filter, con distintos parametros para poder filtrar la lista

2022-05-09 22:35 UTC, franco-marini commented on src/resources/time-sheets.js
> +/// //// PUT METHOD
Remove estos comentarios porque ya con la accion que se utiliza `(GET, POST, PUT, DELETE)` se entiende el metodo que utilizas

2022-05-09 22:35 UTC, franco-marini commented on src/resources/time-sheets.js
> +  if (newTimesheet.id && newTimesheet.user && newTimesheet.day && newTimesheet.project && newTimesheet.task && newTimesheet.workedHours && newTimesheet.check && newTimesheet.manager) {
Revisa esta linea de codigo porque al haber utilizado esto `/* eslint-disable max-len */`, te perjudico el formato del archivo

2022-05-09 22:55 UTC, Juanoauil commented on package.json
> +}
no recibio ningun cambio, no entiendo por que esta como si se hubiese cambiado. lo habia modificado al principio pero desp volvio todo a la normalidad

2022-05-09 22:56 UTC, Juanoauil commented on src/resources/time-sheets.js
> +/* eslint-disable max-len */
ahora lo corrijo

2022-05-09 23:11 UTC, Juanoauil commented on src/resources/time-sheets.js
> +});
mala mia, error de interpretacion

2022-05-10 12:59 UTC, franco-marini commented on src/data/time-sheets.json
> +    },
Los tipos de datos no corresponden a los que tenemos en le modelo de datos

2022-05-10 16:50 UTC, franco-marini commented on src/resources/time-sheets.js
> +  }
Revisa el filter con query params con Lucho que debe ser algo similar a lo que el hizo

2022-05-10 23:14 UTC, franco-marini requested changes

2022-05-10 23:14 UTC, franco-marini commented on src/resources/time-sheets.js
> +  }
Revisa el push porque cuando le mando este objeto:
```json
{
    "id": "1",
    "user": "claudio",
    "day": "monday",
    "project": "buzzdog",
    "workedHours": 4,
    "tasks": [
        {
            "name": "trencher",
            "id": "1",
            "description": "f500",
            "project": "sub-ex",
            "workedHours": 8
        }
    ],
    "check": false,
    "manager": "gan orum"
}
```

Me salta un error

2022-05-10 23:14 UTC, franco-marini commented on src/resources/time-sheets.js
> +  } else {
Me pasa lo mismo aca, revisa que capaz es un tema del cambio de modelo de datos

2022-05-11 20:02 UTC, franco-marini approved these changes

2022-05-11 20:03 UTC, merged