BaSP-TG-29: Unit Testing -> Timesheet (getAll, put, delete)
BaSP-m2022/franco-trackgenix-server pull request #37
Opened 2022-05-23 18:06 UTC by SoofiBaute

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +    const response = await request(app).put(`/time-sheets/${timeSheetId}`).send(
En la linea 65, deberia ser edit y no delete, porque esta dentro de describe put

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +    expect(response.statusCode).toBe(404);
En la linea 82, deberia ser .put y no .delete, porque esta dentro de describe put

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +    expect(response.statusCode).toBe(500);
En la linea 89, deberia ser .put y no .get, porque esta dentro de describe put

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +    expect(response.body.error).toBe(true);
El nombre del test dice que obtiene status 400 pero en el expect de statusCode dice que espera un 500

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +  });
Falta el message

2022-05-23 20:42 UTC, gc796 commented on src/tests/time-sheets.test.js
> +  });
Esto se lo copio a fran tal cual le puso a nico en su pr: "Esta copado como encaraste el test de delete pero te falta verificar si efectivamente se elimino ese projecto de la coleccion de projects. Esto lo podes hacer getAllProjects y verificar que haya X cantidad o haciendo un getById y que devuelva un 404" (Solo que aca seria con timesheet)

2022-05-24 01:11 UTC, gc796 commented on src/tests/time-sheets.test.js
>    });
Eso lo hice en un test aparte, pero si funciona estaria bien, no se que opina franco

2022-05-24 14:58 UTC, franco-marini requested changes
Revisa todos los titulos de los tests que tienen que tener un formato. Te lo deje en algunos comentarios

2022-05-24 14:58 UTC, franco-marini commented on .vscode/settings.json
> +  ],
Esto esta de mas Soofi, lo que podes hacer es agregarlo en las settings de tu usuario de VSCode

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +    // eslint-disable-next-line no-underscore-dangle
Este comentario esta de mas

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +    // eslint-disable-next-line no-underscore-dangle
Este comentario esta de mas

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +  test('populate is working in Employee', async () => {
El titulo del test tiene un forma de escribirlo, la cual es siempre la misma. `It should` o `It shouldn't`

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +  test('populate is working in Task', async () => {
El titulo del test tiene un forma de escribirlo, la cual es siempre la misma. `It should` o `It shouldn't`

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +  test('populate is working in Employee', async () => {
Obviamente deberia decir en este caso `'It should populate the Employee information'`. Esto mismo aplicado para el test que hay debajo

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
> +  });
Fijate que el test debe ser un put y te quedo un get

2022-05-24 14:58 UTC, franco-marini commented on src/tests/time-sheets.test.js
>  });
Estaria bueno hacer un test corroborando que realmente se haya borrado ese usuario. Podes hacer un test con getById y revisar si devuelve un 404 u otra cosa

2022-05-24 15:47 UTC, merged