BaSP-TG-33: Unit Testing - Super Admin
BaSP-m2022/franco-trackgenix-server pull request #38
Opened 2022-05-23 18:42 UTC by gc796

**Methods:**

- GET:
  - getAll
  - getAll with filter by first name
  - getById
- POST
- PUT
- DELETE

2022-05-23 21:19 UTC, LucianoAlarcon commented on src/tests/super-admins.test.js
> +
Gonza esto esta bueno pero si le pasas directamente un `body` en el post y le dejas vacio la parte que queres validar te ahorras tener que crear estas variables al principio. Igual espera a la confirmacion de Fran para cambiar algo.

2022-05-24 16:03 UTC, franco-marini commented on src/tests/super-admins.test.js
> +
Opino lo mismo que Lucho, si lo podes modificar como lo dijo seria un golazo

2022-05-24 16:10 UTC, franco-marini requested changes
Revisa los comentarios que te dejo tambien Lucho

2022-05-24 16:10 UTC, franco-marini commented on src/tests/super-admins.test.js
>    });
El titulo de este test no es el correcto, deberia ser mas especifico en este caso en el test estas haciendo query params

2022-05-24 16:10 UTC, franco-marini commented on src/tests/super-admins.test.js
> +  });
No seria un `invalid id` en todo caso es un not found

2022-05-24 16:10 UTC, franco-marini commented on src/tests/super-admins.test.js
> +  });
Este si seria un invalid id

2022-05-24 16:10 UTC, franco-marini commented on src/tests/super-admins.test.js
> +    });
O haces todos con un objeto que este en la parte superior del test o todos que se le envien el objeto por el send pero no mezcles

2022-05-24 22:52 UTC, Juanoauil commented on src/tests/super-admins.test.js
>    test('It should get super admins list', async () => {
A la ruta le podrias haber indicado el /:id, ya que en algunos tests lo estas usando

2022-05-24 22:54 UTC, Juanoauil commented on src/tests/super-admins.test.js
>      expect(response.body.message).toBe('Super Admins found successfully');
me gusto eso

2022-05-24 22:55 UTC, franco-marini approved these changes

2022-05-24 22:55 UTC, merged