TG-32: unit test to tasks endpoints
BaSP-m2022/franco-trackgenix-server pull request #41
Opened 2022-05-24 02:36 UTC by Juanoauil

2022-05-24 12:52 UTC, LucianoAlarcon commented on src/tests/tasks.test.js
> +describe('Test Tasks routes', () => {
En los describe por lo general va la ruta en especifico que se va a testear, por ej
```suggestion
describe('GET /tasks/get', () => {
```

2022-05-24 12:54 UTC, LucianoAlarcon commented on src/tests/tasks.test.js
> +  });
Y todo esto iría dentro de otro describe que sea
```suggestion
  describe('GET /:id', () =>{
  test('It should return a task by id', async () => {
  });
  });
```

2022-05-24 12:56 UTC, LucianoAlarcon commented on src/tests/tasks.test.js
> +  });
Esto está bien, por ahi te falta testear el error del delete, por ej si te tira un 404 o un 500

2022-05-24 12:59 UTC, LucianoAlarcon commented on src/tests/tasks.test.js
> +  });
Está re bien igual, si dividis eso de los describe para que sea mas facil de leer ya estaría joya 🚀

2022-05-24 16:30 UTC, franco-marini requested changes

2022-05-24 16:30 UTC, franco-marini commented on src/tests/tasks.test.js
> +  });
+2

2022-05-24 16:30 UTC, franco-marini commented on src/tests/tasks.test.js
> +describe('Test Tasks routes', () => {
Claro deberias tener un describe por cada verbo

2022-05-24 22:27 UTC, Juanoauil commented on src/tests/tasks.test.js
> +  });
+3

2022-05-24 22:56 UTC, franco-marini requested changes

2022-05-24 22:56 UTC, franco-marini commented on src/tests/tasks.test.js
> +});
Tenes que hacer un describe separado para el getById y el getAll

2022-05-25 00:01 UTC, LucianoAlarcon commented
🚀​🚀​🚀​🚀​🚀​🚀​🚀​🚀​🚀​🚀​🚀​🚀​

2022-05-25 00:01 UTC, AlejoGF commented
Mas legal que el que vendía las tortas mágicas en el parque españa

2022-05-25 00:02 UTC, Juanoauil commented
nadie vio nada

2022-05-25 00:39 UTC, franco-marini approved these changes

2022-05-25 00:39 UTC, merged