BaSP-TG-120: Update admin, employee and super admin schemas
BaSP-m2022/franco-trackgenix-server pull request #50
Opened 2022-06-28 21:19 UTC by CarVigil

2022-07-01 14:26 UTC, GuidoCerioni approved these changes
🚀

2022-07-01 17:19 UTC, Facund0Fernandez approved these changes

2022-07-01 17:50 UTC, GuidoCerioni requested changes
you should delete password and token from all schemas. We dont save token in database, we are gonna save it on sessionStorage

2022-07-04 17:22 UTC, GuidoCerioni approved these changes

2022-07-04 20:42 UTC, Gearyandres94 approved these changes
🚀

2022-07-04 21:24 UTC, vadalamati approved these changes

2022-07-04 21:27 UTC, merged