BaSP-TG-119: Create/Update Endpoints
BaSP-m2022/franco-trackgenix-server pull request #51
Opened 2022-06-29 01:32 UTC by AlejandroSantini

2022-06-30 17:59 UTC, Facund0Fernandez requested changes

2022-06-30 17:59 UTC, Facund0Fernandez commented on src/controllers/projects.js
> +        // eslint-disable-next-line arrow-body-style
This line should be deleted.

2022-07-01 14:26 UTC, GuidoCerioni commented on src/controllers/projects.js
> +        // eslint-disable-next-line arrow-body-style
We can't figure out a way to delete this line and commit Facu..

2022-07-01 17:16 UTC, Facund0Fernandez approved these changes

2022-07-01 17:47 UTC, GuidoCerioni approved these changes

2022-07-03 19:43 UTC, vadalamati approved these changes
Good job!

2022-07-03 19:44 UTC, merged