BaSP-TG: Feature tasks
BaSP-m2022/franco-trackgenix-server pull request #6
Opened 2022-05-10 21:44 UTC by NicolasFontana

2022-05-10 23:25 UTC, franco-marini requested changes

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.get('/getByProject', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.get('/getById/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.get('/getById/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +});
Este get se puede eliminar ya que la logica es la misma que se implemento en el `getByProject`

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +});
Este get se puede eliminar ya que la logica es la misma que se implemento en el `getByProject`

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +  // eslint-disable-next-line no-console
Elimina este comentario porque no es necesario

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +  // eslint-disable-next-line no-console
Elimina este comentario porque no es necesario

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.post('/addTask', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.post('/addTask', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.delete('/deleteTask/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.delete('/deleteTask/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.put('/modifyTask/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +taskRouter.put('/modifyTask/:id', (req, res) => {
Para mantener un estandar a lo largo de la aplicacion vamos a utilizar como url unicamente `/:id`, excepto en aquellos endpoints que sean mas especificos

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +    tasks = newTasks;
Esta buena la solucion planteada pero con un `.filter` simplificas y optimizas mas el codigo ya que hace una copia del array filtrado por el id

2022-05-10 23:25 UTC, franco-marini commented on src/resources/tasks.js
> +    tasks = newTasks;
Esta buena la solucion planteada pero con un `.filter` simplificas y optimizas mas el codigo ya que hace una copia del array filtrado por el id

2022-05-12 16:44 UTC, franco-marini requested changes

2022-05-12 16:44 UTC, franco-marini commented on src/resources/tasks.js
> +let tasks = require('../data/tasks.json');
La variable `tasks` debe ser `const` en vez de `let`. Y para modificar esta variable se deben crear copias de la misma. Mira los comentarios debajo

2022-05-12 16:44 UTC, franco-marini commented on src/resources/tasks.js
> +    fs.writeFile('src/data/tasks.json', JSON.stringify(tasks), (err) => {
Para no tener el problemas de referencia, siempre se crea en una nueva variable. En este caso deberias hacer:

```js
const filteredTasks = tasks.filter((task) => task.id !== Number(taskId));
    fs.writeFile('src/data/tasks.json', JSON.stringify(filteredTasks), (err) => {
```

De esta manera generas una nueva copia de la lista y no lo modificas por referencia

2022-05-12 16:44 UTC, franco-marini commented on src/resources/tasks.js
> +    fs.writeFile('src/data/tasks.json', JSON.stringify(tasks), (err) => {
Para no tener el problemas de referencia, siempre se crea en una nueva variable. En este caso deberias hacer:

```js
const filteredTasks = tasks.filter((task) => task.id !== Number(taskId));
    filteredTasks.push(taskToModify);
    filteredTasks.sort((a, b) => {
      if (a.id > b.id) {
        return 1;
      }
      if (a.id < b.id) {
        return -1;
      }
      return 0;
    });
    fs.writeFile('src/data/tasks.json', JSON.stringify(filteredTasks), (err) => {
```

De esta manera generas una nueva copia de la lista y no lo modificas por referencia

2022-05-12 19:16 UTC, NicolasFontana commented on src/resources/tasks.js
> +taskRouter.get('/getByProject', (req, res) => {
Fran, no sé si se bugeo o que paso, pero ya lo había corregido en el commit fb2d163

2022-05-12 21:09 UTC, franco-marini approved these changes
🚀

2022-05-12 21:09 UTC, merged